import Foundation

public enum CountryStorefrontCatalog {
    public static let all: [Storefront] = [
        Storefront(countryCode: "AE", displayName: "United Arab Emirates", currencyCode: "AED", storefrontIdentifier: nil),
        Storefront(countryCode: "AG", displayName: "Antigua and Barbuda", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "AI", displayName: "Anguilla", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "AL", displayName: "Albania", currencyCode: "ALL", storefrontIdentifier: nil),
        Storefront(countryCode: "AM", displayName: "Armenia", currencyCode: "AMD", storefrontIdentifier: nil),
        Storefront(countryCode: "AO", displayName: "Angola", currencyCode: "AOA", storefrontIdentifier: nil),
        Storefront(countryCode: "AR", displayName: "Argentina", currencyCode: "ARS", storefrontIdentifier: nil),
        Storefront(countryCode: "AT", displayName: "Austria", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "AU", displayName: "Australia", currencyCode: "AUD", storefrontIdentifier: nil),
        Storefront(countryCode: "AZ", displayName: "Azerbaijan", currencyCode: "AZN", storefrontIdentifier: nil),
        Storefront(countryCode: "BB", displayName: "Barbados", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "BE", displayName: "Belgium", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "BF", displayName: "Burkina Faso", currencyCode: "XOF", storefrontIdentifier: nil),
        Storefront(countryCode: "BG", displayName: "Bulgaria", currencyCode: "BGN", storefrontIdentifier: nil),
        Storefront(countryCode: "BH", displayName: "Bahrain", currencyCode: "BHD", storefrontIdentifier: nil),
        Storefront(countryCode: "BJ", displayName: "Benin", currencyCode: "XOF", storefrontIdentifier: nil),
        Storefront(countryCode: "BM", displayName: "Bermuda", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "BN", displayName: "Brunei Darussalam", currencyCode: "BND", storefrontIdentifier: nil),
        Storefront(countryCode: "BO", displayName: "Bolivia", currencyCode: "BOB", storefrontIdentifier: nil),
        Storefront(countryCode: "BR", displayName: "Brazil", currencyCode: "BRL", storefrontIdentifier: nil),
        Storefront(countryCode: "BS", displayName: "Bahamas", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "BW", displayName: "Botswana", currencyCode: "BWP", storefrontIdentifier: nil),
        Storefront(countryCode: "BY", displayName: "Belarus", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "BZ", displayName: "Belize", currencyCode: "BZD", storefrontIdentifier: nil),
        Storefront(countryCode: "CA", displayName: "Canada", currencyCode: "CAD", storefrontIdentifier: nil),
        Storefront(countryCode: "CG", displayName: "Republic of the Congo", currencyCode: "XAF", storefrontIdentifier: nil),
        Storefront(countryCode: "CH", displayName: "Switzerland", currencyCode: "CHF", storefrontIdentifier: nil),
        Storefront(countryCode: "CL", displayName: "Chile", currencyCode: "CLP", storefrontIdentifier: nil),
        Storefront(countryCode: "CN", displayName: "China Mainland", currencyCode: "CNY", storefrontIdentifier: nil),
        Storefront(countryCode: "CO", displayName: "Colombia", currencyCode: "COP", storefrontIdentifier: nil),
        Storefront(countryCode: "CR", displayName: "Costa Rica", currencyCode: "CRC", storefrontIdentifier: nil),
        Storefront(countryCode: "CV", displayName: "Cape Verde", currencyCode: "CVE", storefrontIdentifier: nil),
        Storefront(countryCode: "CY", displayName: "Cyprus", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "CZ", displayName: "Czechia", currencyCode: "CZK", storefrontIdentifier: nil),
        Storefront(countryCode: "DE", displayName: "Germany", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "DK", displayName: "Denmark", currencyCode: "DKK", storefrontIdentifier: nil),
        Storefront(countryCode: "DM", displayName: "Dominica", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "DO", displayName: "Dominican Republic", currencyCode: "DOP", storefrontIdentifier: nil),
        Storefront(countryCode: "DZ", displayName: "Algeria", currencyCode: "DZD", storefrontIdentifier: nil),
        Storefront(countryCode: "EC", displayName: "Ecuador", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "EE", displayName: "Estonia", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "EG", displayName: "Egypt", currencyCode: "EGP", storefrontIdentifier: nil),
        Storefront(countryCode: "ES", displayName: "Spain", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "FI", displayName: "Finland", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "FJ", displayName: "Fiji", currencyCode: "FJD", storefrontIdentifier: nil),
        Storefront(countryCode: "FM", displayName: "Micronesia", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "FR", displayName: "France", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "GB", displayName: "United Kingdom", currencyCode: "GBP", storefrontIdentifier: nil),
        Storefront(countryCode: "GD", displayName: "Grenada", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "GH", displayName: "Ghana", currencyCode: "GHS", storefrontIdentifier: nil),
        Storefront(countryCode: "GM", displayName: "Gambia", currencyCode: "GMD", storefrontIdentifier: nil),
        Storefront(countryCode: "GR", displayName: "Greece", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "GT", displayName: "Guatemala", currencyCode: "GTQ", storefrontIdentifier: nil),
        Storefront(countryCode: "GW", displayName: "Guinea-Bissau", currencyCode: "XOF", storefrontIdentifier: nil),
        Storefront(countryCode: "GY", displayName: "Guyana", currencyCode: "GYD", storefrontIdentifier: nil),
        Storefront(countryCode: "HK", displayName: "Hong Kong", currencyCode: "HKD", storefrontIdentifier: nil),
        Storefront(countryCode: "HN", displayName: "Honduras", currencyCode: "HNL", storefrontIdentifier: nil),
        Storefront(countryCode: "HR", displayName: "Croatia", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "HU", displayName: "Hungary", currencyCode: "HUF", storefrontIdentifier: nil),
        Storefront(countryCode: "ID", displayName: "Indonesia", currencyCode: "IDR", storefrontIdentifier: nil),
        Storefront(countryCode: "IE", displayName: "Ireland", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "IL", displayName: "Israel", currencyCode: "ILS", storefrontIdentifier: nil),
        Storefront(countryCode: "IN", displayName: "India", currencyCode: "INR", storefrontIdentifier: nil),
        Storefront(countryCode: "IQ", displayName: "Iraq", currencyCode: "IQD", storefrontIdentifier: nil),
        Storefront(countryCode: "IS", displayName: "Iceland", currencyCode: "ISK", storefrontIdentifier: nil),
        Storefront(countryCode: "IT", displayName: "Italy", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "JM", displayName: "Jamaica", currencyCode: "JMD", storefrontIdentifier: nil),
        Storefront(countryCode: "JO", displayName: "Jordan", currencyCode: "JOD", storefrontIdentifier: nil),
        Storefront(countryCode: "JP", displayName: "Japan", currencyCode: "JPY", storefrontIdentifier: nil),
        Storefront(countryCode: "KE", displayName: "Kenya", currencyCode: "KES", storefrontIdentifier: nil),
        Storefront(countryCode: "KG", displayName: "Kyrgyzstan", currencyCode: "KGS", storefrontIdentifier: nil),
        Storefront(countryCode: "KH", displayName: "Cambodia", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "KN", displayName: "Saint Kitts and Nevis", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "KR", displayName: "South Korea", currencyCode: "KRW", storefrontIdentifier: nil),
        Storefront(countryCode: "KW", displayName: "Kuwait", currencyCode: "KWD", storefrontIdentifier: nil),
        Storefront(countryCode: "KY", displayName: "Cayman Islands", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "KZ", displayName: "Kazakhstan", currencyCode: "KZT", storefrontIdentifier: nil),
        Storefront(countryCode: "LA", displayName: "Laos", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "LB", displayName: "Lebanon", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "LC", displayName: "Saint Lucia", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "LK", displayName: "Sri Lanka", currencyCode: "LKR", storefrontIdentifier: nil),
        Storefront(countryCode: "LR", displayName: "Liberia", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "LT", displayName: "Lithuania", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "LU", displayName: "Luxembourg", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "LV", displayName: "Latvia", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "MD", displayName: "Moldova", currencyCode: "MDL", storefrontIdentifier: nil),
        Storefront(countryCode: "MG", displayName: "Madagascar", currencyCode: "MGA", storefrontIdentifier: nil),
        Storefront(countryCode: "MK", displayName: "North Macedonia", currencyCode: "MKD", storefrontIdentifier: nil),
        Storefront(countryCode: "ML", displayName: "Mali", currencyCode: "XOF", storefrontIdentifier: nil),
        Storefront(countryCode: "MM", displayName: "Myanmar", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "MN", displayName: "Mongolia", currencyCode: "MNT", storefrontIdentifier: nil),
        Storefront(countryCode: "MO", displayName: "Macao", currencyCode: "MOP", storefrontIdentifier: nil),
        Storefront(countryCode: "MR", displayName: "Mauritania", currencyCode: "MRU", storefrontIdentifier: nil),
        Storefront(countryCode: "MS", displayName: "Montserrat", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "MT", displayName: "Malta", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "MU", displayName: "Mauritius", currencyCode: "MUR", storefrontIdentifier: nil),
        Storefront(countryCode: "MV", displayName: "Maldives", currencyCode: "MVR", storefrontIdentifier: nil),
        Storefront(countryCode: "MW", displayName: "Malawi", currencyCode: "MWK", storefrontIdentifier: nil),
        Storefront(countryCode: "MX", displayName: "Mexico", currencyCode: "MXN", storefrontIdentifier: nil),
        Storefront(countryCode: "MY", displayName: "Malaysia", currencyCode: "MYR", storefrontIdentifier: nil),
        Storefront(countryCode: "MZ", displayName: "Mozambique", currencyCode: "MZN", storefrontIdentifier: nil),
        Storefront(countryCode: "NA", displayName: "Namibia", currencyCode: "NAD", storefrontIdentifier: nil),
        Storefront(countryCode: "NE", displayName: "Niger", currencyCode: "XOF", storefrontIdentifier: nil),
        Storefront(countryCode: "NG", displayName: "Nigeria", currencyCode: "NGN", storefrontIdentifier: nil),
        Storefront(countryCode: "NI", displayName: "Nicaragua", currencyCode: "NIO", storefrontIdentifier: nil),
        Storefront(countryCode: "NL", displayName: "Netherlands", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "NO", displayName: "Norway", currencyCode: "NOK", storefrontIdentifier: nil),
        Storefront(countryCode: "NP", displayName: "Nepal", currencyCode: "NPR", storefrontIdentifier: nil),
        Storefront(countryCode: "NZ", displayName: "New Zealand", currencyCode: "NZD", storefrontIdentifier: nil),
        Storefront(countryCode: "OM", displayName: "Oman", currencyCode: "OMR", storefrontIdentifier: nil),
        Storefront(countryCode: "PA", displayName: "Panama", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "PE", displayName: "Peru", currencyCode: "PEN", storefrontIdentifier: nil),
        Storefront(countryCode: "PG", displayName: "Papua New Guinea", currencyCode: "PGK", storefrontIdentifier: nil),
        Storefront(countryCode: "PH", displayName: "Philippines", currencyCode: "PHP", storefrontIdentifier: nil),
        Storefront(countryCode: "PK", displayName: "Pakistan", currencyCode: "PKR", storefrontIdentifier: nil),
        Storefront(countryCode: "PL", displayName: "Poland", currencyCode: "PLN", storefrontIdentifier: nil),
        Storefront(countryCode: "PT", displayName: "Portugal", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "PW", displayName: "Palau", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "PY", displayName: "Paraguay", currencyCode: "PYG", storefrontIdentifier: nil),
        Storefront(countryCode: "QA", displayName: "Qatar", currencyCode: "QAR", storefrontIdentifier: nil),
        Storefront(countryCode: "RO", displayName: "Romania", currencyCode: "RON", storefrontIdentifier: nil),
        Storefront(countryCode: "RS", displayName: "Serbia", currencyCode: "RSD", storefrontIdentifier: nil),
        Storefront(countryCode: "RU", displayName: "Russia", currencyCode: "RUB", storefrontIdentifier: nil),
        Storefront(countryCode: "SA", displayName: "Saudi Arabia", currencyCode: "SAR", storefrontIdentifier: nil),
        Storefront(countryCode: "SB", displayName: "Solomon Islands", currencyCode: "SBD", storefrontIdentifier: nil),
        Storefront(countryCode: "SC", displayName: "Seychelles", currencyCode: "SCR", storefrontIdentifier: nil),
        Storefront(countryCode: "SE", displayName: "Sweden", currencyCode: "SEK", storefrontIdentifier: nil),
        Storefront(countryCode: "SG", displayName: "Singapore", currencyCode: "SGD", storefrontIdentifier: nil),
        Storefront(countryCode: "SI", displayName: "Slovenia", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "SK", displayName: "Slovakia", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "SL", displayName: "Sierra Leone", currencyCode: "SLL", storefrontIdentifier: nil),
        Storefront(countryCode: "SN", displayName: "Senegal", currencyCode: "XOF", storefrontIdentifier: nil),
        Storefront(countryCode: "SR", displayName: "Suriname", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "ST", displayName: "Sao Tome and Principe", currencyCode: "STN", storefrontIdentifier: nil),
        Storefront(countryCode: "SV", displayName: "El Salvador", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "SZ", displayName: "Eswatini", currencyCode: "SZL", storefrontIdentifier: nil),
        Storefront(countryCode: "TC", displayName: "Turks and Caicos", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "TD", displayName: "Chad", currencyCode: "XAF", storefrontIdentifier: nil),
        Storefront(countryCode: "TH", displayName: "Thailand", currencyCode: "THB", storefrontIdentifier: nil),
        Storefront(countryCode: "TJ", displayName: "Tajikistan", currencyCode: "TJS", storefrontIdentifier: nil),
        Storefront(countryCode: "TM", displayName: "Turkmenistan", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "TN", displayName: "Tunisia", currencyCode: "TND", storefrontIdentifier: nil),
        Storefront(countryCode: "TO", displayName: "Tonga", currencyCode: "TOP", storefrontIdentifier: nil),
        Storefront(countryCode: "TR", displayName: "Turkiye", currencyCode: "TRY", storefrontIdentifier: nil),
        Storefront(countryCode: "TT", displayName: "Trinidad and Tobago", currencyCode: "TTD", storefrontIdentifier: nil),
        Storefront(countryCode: "TW", displayName: "Taiwan", currencyCode: "TWD", storefrontIdentifier: nil),
        Storefront(countryCode: "TZ", displayName: "Tanzania", currencyCode: "TZS", storefrontIdentifier: nil),
        Storefront(countryCode: "UA", displayName: "Ukraine", currencyCode: "UAH", storefrontIdentifier: nil),
        Storefront(countryCode: "UG", displayName: "Uganda", currencyCode: "UGX", storefrontIdentifier: nil),
        Storefront(countryCode: "US", displayName: "United States", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "UY", displayName: "Uruguay", currencyCode: "UYU", storefrontIdentifier: nil),
        Storefront(countryCode: "UZ", displayName: "Uzbekistan", currencyCode: "UZS", storefrontIdentifier: nil),
        Storefront(countryCode: "VC", displayName: "Saint Vincent and the Grenadines", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "VE", displayName: "Venezuela", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "VG", displayName: "British Virgin Islands", currencyCode: "USD", storefrontIdentifier: nil),
        Storefront(countryCode: "VN", displayName: "Vietnam", currencyCode: "VND", storefrontIdentifier: nil),
        Storefront(countryCode: "VU", displayName: "Vanuatu", currencyCode: "VUV", storefrontIdentifier: nil),
        Storefront(countryCode: "XK", displayName: "Kosovo", currencyCode: "EUR", storefrontIdentifier: nil),
        Storefront(countryCode: "YE", displayName: "Yemen", currencyCode: "YER", storefrontIdentifier: nil),
        Storefront(countryCode: "ZA", displayName: "South Africa", currencyCode: "ZAR", storefrontIdentifier: nil),
        Storefront(countryCode: "ZM", displayName: "Zambia", currencyCode: "ZMW", storefrontIdentifier: nil),
        Storefront(countryCode: "ZW", displayName: "Zimbabwe", currencyCode: "USD", storefrontIdentifier: nil)
    ].sorted { $0.displayName.localizedCaseInsensitiveCompare($1.displayName) == .orderedAscending }

    public static var defaultSelection: Set<String> {
        Set(all.map(\.countryCode))
    }
}
